// Code generated by logcopter-gen; DO NOT EDIT.

package action

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.go-go-agent-action.internal.action")
